version: '3'
services:

  gateway:
    build: ./gateway
    # Add any additional configuration for gateway service here
    ports:
      - 80:80
      - 443:443
    depends_on:
      - m1
      - m2
      - auth
      
  m1:
    build: ./services/m1
    # Add any additional configuration for m1 service here
    ports:
      - 3000:3000

  m2:
    build: ./services/m2
    # Add any additional configuration for m2 service here
    ports:
      - 4000:4000

  auth:
    build: ./auth
    # Add any additional configuration for auth service here
    ports:
      - 5000:5000