networks:
  nginx-easy-gateway:
    external: false

services:

  gateway:
    image: mynginx:latest
    container_name: gateway
    hostname: gateway
    networks:
      - nginx-easy-gateway
    ports:
      - 80:80
    depends_on:
      - m1
      - m2
      - auth
    volumes:
      - ./gateway/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/usr/share/nginx/html
      
  m1:
    image: mynodejs:latest
    container_name: m1
    hostname: m1    
    networks:
      - nginx-easy-gateway
    volumes:
      - ./services/m1:/m1
    expose:
      - 3000
    working_dir: /m1
    command: npm run start:dev

  m2:
    image: mynodejs:latest
    container_name: m2
    hostname: m2    
    networks:
      - nginx-easy-gateway
    volumes:
      - ./services/m2:/m2
    expose:
      - 3000
    working_dir: /m2
    command: npm run start:dev

  auth:
    image: mynodejs:latest
    container_name: auth
    hostname: auth    
    networks:
      - nginx-easy-gateway
    volumes:
      - ./auth:/auth
    expose:
      - 3000
    working_dir: /auth
    command: npm run start:dev